### ISSUE TITLE
'peg_idx' is not defined

### ISSUE THREAD

**Issue by vedantdave97** [callmeray/ManiSkill-ViTac2024#10]
```
File "/home/vedant/mvitac_man/ManiSkill-ViTac2024/scripts/../envs/peg_insertion.py", line 479, in reset
    offset = self.__initialize__(offset, peg_idx)
NameError: name 'peg_idx' is not defined
```
https://github.com/callmeray/ManiSkill-ViTac2024/blob/4be291bf7b30a0be823f2cbfa85a14d20a4e608b/envs/peg_insertion.py#L479

I get this error from the updated repo. It was not present in the old one. Can you please check that if the argument peg_idx is added correctly to the initialize function.

**Comment by chuanyune** [comment]
Thank you for your question. We have fixed this bug already.

**Comment by vedantdave97** [comment]
Thank you. It works now.
