### ISSUE TITLE
KeyError: 'lr_schedule'

### ISSUE THREAD

**Issue by csufangyu** [callmeray/ManiSkill-ViTac2024#13]
hi，when I want to run your demo,but it get a error.
`File "scripts/peg_insertion_sim_evaluation.py", line 133, in <module>
    lr_schedule=data["lr_schedule"],
KeyError: 'lr_schedule'`

**Comment by chuanyune** [comment]
Please update to the newest git commit and try again.

**Comment by csufangyu** [comment]
> Please update to the newest git commit and try again.

thanks your reply, but it is same error when I run:`python scripts/peg_insertion_sim_evaluation.py --key`. I use the fellow command to update :`git fetch origin` and `git merge origin/main`

**Comment by chuanyune** [comment]
Are you using the best_model provided by us for evaluation, or your own trained best_model? Have you made any modifications to the code? If so, please provide the code after your modifications.

**Comment by csufangyu** [comment]
> Are you using the best_model provided by us for evaluation, or your own trained best_model? Have you made any modifications to the code? If so, please provide the code after your modifications.

I did not make any modifications. I use the best_model is provided by yours. and I print the data.keys(),and the output is `dict_keys(['policy_class', 'verbose', 'policy_kwargs', 'num_timesteps', '_total_timesteps', '_num_timesteps_at_start', 'seed', 'action_noise', 'start_time', 'learning_rate', 'tensorboard_log', '_last_obs', '_last_episode_starts', '_last_original_obs', '_episode_num', 'use_sde', 'sde_sample_freq', '_current_progress_remaining', '_stats_window_size', 'ep_info_buffer', 'ep_success_buffer', '_n_updates', 'observation_space', 'action_space', 'n_envs', 'buffer_size', 'batch_size', 'learning_starts', 'tau', 'gamma', 'gradient_steps', 'optimize_memory_usage', 'replay_buffer_class', 'replay_buffer_kwargs', 'train_freq', 'use_sde_at_warmup', 'policy_delay', 'target_noise_clip', 'target_policy_noise', 'actor_batch_norm_stats', 'critic_batch_norm_stats', 'actor_batch_norm_stats_target', 'critic_batch_norm_stats_target'])` . The “lr_schedule” is not found.

**Comment by chuanyune** [comment]
Are you the version submitted this time? If not, please check out this version. After multiple tests, I found that there are still no issues.
![image](https://github.com/callmeray/ManiSkill-ViTac2024/assets/131238818/602c2e36-24e1-4f90-82c7-607f64730eec)

**Comment by csufangyu** [comment]
yes, can you share the best_model.pth? the best_model provided in repo, the“lr_schedule” is not found.  Maybe you can print(data.keys)

**Comment by chuanyune** [comment]
Hello, I printed data.keys and found the required lr_schedule. Can you please send me an email so that we can communicate in a simpler way to identify where the issue might be?  maniskill.vitac@gmail.com

**Comment by csufangyu** [comment]
ok, I have sent the email. Thanks !

**Comment by chuanyune** [comment]
If there are any issues, please pull the code to your local machine and then proceed with testing.
