### ISSUE TITLE
ModuleNotFoundError: No module named 'sapienipc'

### ISSUE THREAD

**Issue by T21512** [callmeray/ManiSkill-ViTac2024#2]
Where can we download sapienipc from?

**Comment by chuanyune** [comment]
You can install it according to the readme, and of course the link is herehttps://github.com/Rabbit-Hu/sapienipc-exp

**Comment by T21512** [comment]
usage: peg_insertion_sim_evaluation.py [-h] [--key KEY] --render_rgb RENDER_RGB
peg_insertion_sim_evaluation.py: error: the following arguments are required: --render_rgb

May I ask how this key value is obtained?

**Comment by chuanyune** [comment]
Can you please provide me with this information if you are having problems running that script? @2655519028

**Comment by chuanyune** [comment]
"render_rgb" refers to whether or not to select rendering tactile sensor RGB images. If not, it would be "false." @2655519028

**Comment by callmeray** [comment]
> usage: peg_insertion_sim_evaluation.py [-h] [--key KEY] --render_rgb RENDER_RGB peg_insertion_sim_evaluation.py: error: the following arguments are required: --render_rgb
> 
> May I ask how this key value is obtained?

you will receive a key upon registration. For detailed instructions on how to register, please refer to the following link: [ManiSkill-ViTac Challenge 2024 Registration](https://ai-workshops.github.io/maniskill-vitac-challenge-2024/index.html#start).
