### ISSUE TITLE
Is using CUDA mandatory for the challenge?

### ISSUE THREAD

**Issue by cemoke** [callmeray/ManiSkill-ViTac2024#4]
Hi,

I want to participate in the challenge. However, I use a MacBook with an M1 processor (GPU is not Nvidia) and thus can not install the repo. 

Is using an Nvidia GPU a hard constraint for the challenge or is it possible to modify the repo such that it can run without using CUDA but either CPU or other GPU devices such as MPS (https://pytorch.org/docs/stable/notes/mps.html)?

Best,

Cem

**Comment by chuanyune** [comment]
Sorry,this project requires the use of warp, which is only compatible with Nvidia GPU. Therefore, configuring it on a Mac is not feasible.
