### ISSUE TITLE
Discord link failed Again and some questions

### ISSUE THREAD

**Issue by jiangranlv** [callmeray/ManiSkill-ViTac2024#7]
1. discord link failed
2. Can we get the pretrained encoder weight before RL?
3. The simulator is extremely slow against paper reports. I wonder how to parallel 20 envs for sampling like paper reports. In my server, 2 envs comes with the CPU computation bottleneck.

Thank you!

**Comment by callmeray** [comment]
1. please use the new link: https://discord.gg/6W8scShT
2. policy with pretrained weight will be released in a few days, before the sim evaluation begins.
3. The released simulator's implementation is different from the paper.

**Comment by jiangranlv** [comment]
> 1. please use the new link: https://discord.gg/6W8scShT
> 
>     2. policy with pretrained weight will be released in a few days, before the sim evaluation begins.
> 
>     3. The released simulator's implementation is different from the paper.

OK, Thanks for the reply! So I'm interested what's the core difference of the simulator between released version and paper version which results the speed gap. And will the faster version be released? It's meaningful for both this challenge and further research. Thanks again.

**Comment by callmeray** [comment]
The paper is implemented using C and runs on CPUs, and the repo is implemented using warp and runs on GPUs. The model and principle are identical.

**Comment by csufangyu** [comment]
hi, discord link failed, now! can you share new link?
